// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRUabc9GgHbAIRZv7x378cd3zwW7dfWqI',
    appId: '1:78273597272:web:ed80bfc849e79fd5b61f2d',
    messagingSenderId: '78273597272',
    projectId: 'oficinadobolo-app',
    authDomain: 'oficinadobolo-app.firebaseapp.com',
    storageBucket: 'oficinadobolo-app.firebasestorage.app',
    measurementId: 'G-3E93TQB2QK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIx2WEYV8_m0LTkZuMESbXXcawQTmn4cQ',
    appId: '1:78273597272:android:4fa71fefd8a2e99ab61f2d',
    messagingSenderId: '78273597272',
    projectId: 'oficinadobolo-app',
    storageBucket: 'oficinadobolo-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiPgW75zHIsn5MiU00Kvm-9QqQbcj0lr4',
    appId: '1:78273597272:ios:5db701ac9f871030b61f2d',
    messagingSenderId: '78273597272',
    projectId: 'oficinadobolo-app',
    storageBucket: 'oficinadobolo-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterGames',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRUabc9GgHbAIRZv7x378cd3zwW7dfWqI',
    appId: '1:78273597272:web:0553444bf7c885c4b61f2d',
    messagingSenderId: '78273597272',
    projectId: 'oficinadobolo-app',
    authDomain: 'oficinadobolo-app.firebaseapp.com',
    storageBucket: 'oficinadobolo-app.firebasestorage.app',
    measurementId: 'G-ZL9YP6N8LP',
  );
}
